USE [master]
GO
/****** Object:  Database [atzoum01]    Script Date: 11/21/2020 11:38:46 PM ******/
CREATE DATABASE [atzoum01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'atzoum01_Data', FILENAME = N'H:\SQLData\atzoum01_Data.mdf' , SIZE = 8192KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'atzoum01_Log', FILENAME = N'E:\SQLLogs\atzoum01_Log.ldf' , SIZE = 2048KB , MAXSIZE = 3072KB , FILEGROWTH = 1024KB )
GO
ALTER DATABASE [atzoum01] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [atzoum01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [atzoum01] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [atzoum01] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [atzoum01] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [atzoum01] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [atzoum01] SET ARITHABORT OFF 
GO
ALTER DATABASE [atzoum01] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [atzoum01] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [atzoum01] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [atzoum01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [atzoum01] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [atzoum01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [atzoum01] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [atzoum01] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [atzoum01] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [atzoum01] SET  ENABLE_BROKER 
GO
ALTER DATABASE [atzoum01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [atzoum01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [atzoum01] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [atzoum01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [atzoum01] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [atzoum01] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [atzoum01] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [atzoum01] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [atzoum01] SET  MULTI_USER 
GO
ALTER DATABASE [atzoum01] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [atzoum01] SET DB_CHAINING OFF 
GO
ALTER DATABASE [atzoum01] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [atzoum01] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [atzoum01] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [atzoum01] SET QUERY_STORE = OFF
GO
USE [atzoum01]
GO
/****** Object:  User [atzoum01]    Script Date: 11/21/2020 11:38:47 PM ******/
CREATE USER [atzoum01] FOR LOGIN [atzoum01] WITH DEFAULT_SCHEMA=[atzoum01]
GO
ALTER ROLE [db_owner] ADD MEMBER [atzoum01]
GO
/****** Object:  Schema [atzoum01]    Script Date: 11/21/2020 11:38:47 PM ******/
CREATE SCHEMA [atzoum01]
GO
/****** Object:  Table [atzoum01].[ALBUM]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[ALBUM](
	[album_id] [int] NOT NULL,
	[album_name] [nvarchar](50) NOT NULL,
	[privacy] [nvarchar](50) NOT NULL,
	[description] [nvarchar](50) NULL,
	[city_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
 CONSTRAINT [PK_ALBUM] PRIMARY KEY CLUSTERED 
(
	[album_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[ALBUM_COMMENTS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[ALBUM_COMMENTS](
	[album_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
	[comments] [nvarchar](50) NULL,
 CONSTRAINT [PK_ALBUM_COMMENTS] PRIMARY KEY CLUSTERED 
(
	[album_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[CITY]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[CITY](
	[city_id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED 
(
	[city_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[COMPANY]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[COMPANY](
	[company_id] [int] NOT NULL,
	[company_name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_COMPANY] PRIMARY KEY CLUSTERED 
(
	[company_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[EVENT_RESPONSES]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[EVENT_RESPONSES](
	[event_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
	[response] [nvarchar](50) NULL,
 CONSTRAINT [PK_EVENT_RESPONSES] PRIMARY KEY CLUSTERED 
(
	[event_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[EVENTS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[EVENTS](
	[event_id] [int] NOT NULL,
	[event_name] [nvarchar](50) NOT NULL,
	[privacy] [nvarchar](50) NOT NULL,
	[location] [nvarchar](50) NULL,
	[start_time] [time](7) NULL,
	[end_time] [time](7) NULL,
	[description] [nvarchar](50) NULL,
	[owner_id] [int] NOT NULL,
	[venue] [int] NOT NULL,
 CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED 
(
	[event_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[FRIENDS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[FRIENDS](
	[profile_1] [int] NOT NULL,
	[profile_2] [int] NOT NULL,
 CONSTRAINT [PK_FRIENDS] PRIMARY KEY CLUSTERED 
(
	[profile_1] ASC,
	[profile_2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[INTERESTS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[INTERESTS](
	[interest_id] [int] NOT NULL,
	[interest_name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_INTERESTS] PRIMARY KEY CLUSTERED 
(
	[interest_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[LIKES]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[LIKES](
	[photo_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
 CONSTRAINT [PK_LIKES] PRIMARY KEY CLUSTERED 
(
	[photo_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[LINKS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[LINKS](
	[link_id] [int] NOT NULL,
	[link] [nvarchar](50) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[caption] [nvarchar](50) NULL,
	[description] [nvarchar](50) NULL,
	[message] [nvarchar](50) NULL,
	[from_user] [int] NOT NULL,
 CONSTRAINT [PK_LINKS] PRIMARY KEY CLUSTERED 
(
	[link_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[PHOTOS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[PHOTOS](
	[photo_id] [int] NOT NULL,
	[height] [int] NULL,
	[width] [int] NULL,
	[source] [nvarchar](50) NULL,
	[from_user] [int] NOT NULL,
	[album_id] [int] NULL,
 CONSTRAINT [PK_PHOTOS] PRIMARY KEY CLUSTERED 
(
	[photo_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[PROFILE]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[PROFILE](
	[profile_id] [int] NOT NULL,
	[last_name] [nvarchar](50) NOT NULL,
	[first_name] [nvarchar](50) NOT NULL,
	[birthday] [smalldatetime] NOT NULL,
	[quotes] [nvarchar](50) NULL,
	[website] [nvarchar](50) NULL,
	[email] [nvarchar](50) NOT NULL,
	[password] [nvarchar](50) NOT NULL,
	[born_at] [int] NOT NULL,
	[lives_in] [int] NOT NULL,
 CONSTRAINT [PK_PROFILE] PRIMARY KEY CLUSTERED 
(
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_PROFILE_password] UNIQUE NONCLUSTERED 
(
	[password] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[REQUESTS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[REQUESTS](
	[profile_1] [int] NOT NULL,
	[profile_2] [int] NOT NULL,
	[states] [nvarchar](1) NULL,
 CONSTRAINT [PK_REQUESTS] PRIMARY KEY CLUSTERED 
(
	[profile_1] ASC,
	[profile_2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[SCHOOLS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[SCHOOLS](
	[school_id] [int] NOT NULL,
	[school_name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SCHOOLS] PRIMARY KEY CLUSTERED 
(
	[school_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[STUDIED_AT]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[STUDIED_AT](
	[school_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
 CONSTRAINT [PK_STUDIED_AT] PRIMARY KEY CLUSTERED 
(
	[school_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[TABLES]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[TABLES](
	[interest_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
 CONSTRAINT [PK_TABLES] PRIMARY KEY CLUSTERED 
(
	[interest_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[VIDEO]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[VIDEO](
	[video_id] [int] NOT NULL,
	[message] [nvarchar](100) NULL,
	[video] [varbinary](max) NOT NULL,
	[description] [nvarchar](100) NULL,
	[profile_id] [int] NOT NULL,
 CONSTRAINT [PK_VIDEO] PRIMARY KEY CLUSTERED 
(
	[video_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[VIDEO_COMMENTS]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[VIDEO_COMMENTS](
	[video_id] [int] NOT NULL,
	[profile_id] [int] NOT NULL,
	[comments] [nvarchar](50) NULL,
 CONSTRAINT [PK_VDEO_COMMENTS] PRIMARY KEY CLUSTERED 
(
	[video_id] ASC,
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [atzoum01].[WORKED_FOR]    Script Date: 11/21/2020 11:38:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [atzoum01].[WORKED_FOR](
	[profile_id] [int] NOT NULL,
	[company_id] [int] NOT NULL,
 CONSTRAINT [PK_WORKED_FOR] PRIMARY KEY CLUSTERED 
(
	[profile_id] ASC,
	[company_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [atzoum01].[ALBUM]  WITH CHECK ADD  CONSTRAINT [FK_ALBUM_CITY] FOREIGN KEY([city_id])
REFERENCES [atzoum01].[CITY] ([city_id])
GO
ALTER TABLE [atzoum01].[ALBUM] CHECK CONSTRAINT [FK_ALBUM_CITY]
GO
ALTER TABLE [atzoum01].[ALBUM]  WITH CHECK ADD  CONSTRAINT [FK_ALBUM_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[ALBUM] CHECK CONSTRAINT [FK_ALBUM_PROFILE]
GO
ALTER TABLE [atzoum01].[ALBUM_COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_ALBUM_COMMENTS_ALBUM] FOREIGN KEY([album_id])
REFERENCES [atzoum01].[ALBUM] ([album_id])
GO
ALTER TABLE [atzoum01].[ALBUM_COMMENTS] CHECK CONSTRAINT [FK_ALBUM_COMMENTS_ALBUM]
GO
ALTER TABLE [atzoum01].[ALBUM_COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_ALBUM_COMMENTS_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[ALBUM_COMMENTS] CHECK CONSTRAINT [FK_ALBUM_COMMENTS_PROFILE]
GO
ALTER TABLE [atzoum01].[EVENT_RESPONSES]  WITH CHECK ADD  CONSTRAINT [FK_EVENT_RESPONSES_EVENTS] FOREIGN KEY([event_id])
REFERENCES [atzoum01].[EVENTS] ([event_id])
GO
ALTER TABLE [atzoum01].[EVENT_RESPONSES] CHECK CONSTRAINT [FK_EVENT_RESPONSES_EVENTS]
GO
ALTER TABLE [atzoum01].[EVENT_RESPONSES]  WITH CHECK ADD  CONSTRAINT [FK_EVENT_RESPONSES_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[EVENT_RESPONSES] CHECK CONSTRAINT [FK_EVENT_RESPONSES_PROFILE]
GO
ALTER TABLE [atzoum01].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_CITY] FOREIGN KEY([venue])
REFERENCES [atzoum01].[CITY] ([city_id])
GO
ALTER TABLE [atzoum01].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_CITY]
GO
ALTER TABLE [atzoum01].[EVENTS]  WITH CHECK ADD  CONSTRAINT [FK_EVENTS_PROFILE] FOREIGN KEY([owner_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[EVENTS] CHECK CONSTRAINT [FK_EVENTS_PROFILE]
GO
ALTER TABLE [atzoum01].[FRIENDS]  WITH CHECK ADD  CONSTRAINT [FK_FRIENDS_PROFILE] FOREIGN KEY([profile_1])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[FRIENDS] CHECK CONSTRAINT [FK_FRIENDS_PROFILE]
GO
ALTER TABLE [atzoum01].[FRIENDS]  WITH CHECK ADD  CONSTRAINT [FK_FRIENDS_PROFILE1] FOREIGN KEY([profile_2])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[FRIENDS] CHECK CONSTRAINT [FK_FRIENDS_PROFILE1]
GO
ALTER TABLE [atzoum01].[LIKES]  WITH CHECK ADD  CONSTRAINT [FK_LIKES_PHOTOS] FOREIGN KEY([photo_id])
REFERENCES [atzoum01].[PHOTOS] ([photo_id])
GO
ALTER TABLE [atzoum01].[LIKES] CHECK CONSTRAINT [FK_LIKES_PHOTOS]
GO
ALTER TABLE [atzoum01].[LIKES]  WITH CHECK ADD  CONSTRAINT [FK_LIKES_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[LIKES] CHECK CONSTRAINT [FK_LIKES_PROFILE]
GO
ALTER TABLE [atzoum01].[LINKS]  WITH CHECK ADD  CONSTRAINT [FK_LINKS_PROFILE] FOREIGN KEY([from_user])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[LINKS] CHECK CONSTRAINT [FK_LINKS_PROFILE]
GO
ALTER TABLE [atzoum01].[PHOTOS]  WITH CHECK ADD  CONSTRAINT [FK_PHOTOS_ALBUM] FOREIGN KEY([album_id])
REFERENCES [atzoum01].[ALBUM] ([album_id])
GO
ALTER TABLE [atzoum01].[PHOTOS] CHECK CONSTRAINT [FK_PHOTOS_ALBUM]
GO
ALTER TABLE [atzoum01].[PHOTOS]  WITH CHECK ADD  CONSTRAINT [FK_PHOTOS_PROFILE] FOREIGN KEY([from_user])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[PHOTOS] CHECK CONSTRAINT [FK_PHOTOS_PROFILE]
GO
ALTER TABLE [atzoum01].[PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_PROFILE_CITY] FOREIGN KEY([born_at])
REFERENCES [atzoum01].[CITY] ([city_id])
GO
ALTER TABLE [atzoum01].[PROFILE] CHECK CONSTRAINT [FK_PROFILE_CITY]
GO
ALTER TABLE [atzoum01].[PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_PROFILE_CITY1] FOREIGN KEY([lives_in])
REFERENCES [atzoum01].[CITY] ([city_id])
GO
ALTER TABLE [atzoum01].[PROFILE] CHECK CONSTRAINT [FK_PROFILE_CITY1]
GO
ALTER TABLE [atzoum01].[REQUESTS]  WITH CHECK ADD  CONSTRAINT [FK_REQUESTS_PROFILE] FOREIGN KEY([profile_1])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[REQUESTS] CHECK CONSTRAINT [FK_REQUESTS_PROFILE]
GO
ALTER TABLE [atzoum01].[REQUESTS]  WITH CHECK ADD  CONSTRAINT [FK_REQUESTS_PROFILE1] FOREIGN KEY([profile_2])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[REQUESTS] CHECK CONSTRAINT [FK_REQUESTS_PROFILE1]
GO
ALTER TABLE [atzoum01].[STUDIED_AT]  WITH CHECK ADD  CONSTRAINT [FK_STUDIED_AT_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[STUDIED_AT] CHECK CONSTRAINT [FK_STUDIED_AT_PROFILE]
GO
ALTER TABLE [atzoum01].[STUDIED_AT]  WITH CHECK ADD  CONSTRAINT [FK_STUDIED_AT_SCHOOLS] FOREIGN KEY([school_id])
REFERENCES [atzoum01].[SCHOOLS] ([school_id])
GO
ALTER TABLE [atzoum01].[STUDIED_AT] CHECK CONSTRAINT [FK_STUDIED_AT_SCHOOLS]
GO
ALTER TABLE [atzoum01].[TABLES]  WITH CHECK ADD  CONSTRAINT [FK_TABLES_INTERESTS] FOREIGN KEY([interest_id])
REFERENCES [atzoum01].[INTERESTS] ([interest_id])
GO
ALTER TABLE [atzoum01].[TABLES] CHECK CONSTRAINT [FK_TABLES_INTERESTS]
GO
ALTER TABLE [atzoum01].[TABLES]  WITH CHECK ADD  CONSTRAINT [FK_TABLES_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[TABLES] CHECK CONSTRAINT [FK_TABLES_PROFILE]
GO
ALTER TABLE [atzoum01].[VIDEO]  WITH CHECK ADD  CONSTRAINT [FK_VIDEO_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[VIDEO] CHECK CONSTRAINT [FK_VIDEO_PROFILE]
GO
ALTER TABLE [atzoum01].[VIDEO_COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_VIDEO_COMMENTS_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[VIDEO_COMMENTS] CHECK CONSTRAINT [FK_VIDEO_COMMENTS_PROFILE]
GO
ALTER TABLE [atzoum01].[VIDEO_COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_VIDEO_COMMENTS_VIDEO] FOREIGN KEY([video_id])
REFERENCES [atzoum01].[VIDEO] ([video_id])
GO
ALTER TABLE [atzoum01].[VIDEO_COMMENTS] CHECK CONSTRAINT [FK_VIDEO_COMMENTS_VIDEO]
GO
ALTER TABLE [atzoum01].[WORKED_FOR]  WITH CHECK ADD  CONSTRAINT [FK_WORKED_FOR_COMPANY] FOREIGN KEY([company_id])
REFERENCES [atzoum01].[COMPANY] ([company_id])
GO
ALTER TABLE [atzoum01].[WORKED_FOR] CHECK CONSTRAINT [FK_WORKED_FOR_COMPANY]
GO
ALTER TABLE [atzoum01].[WORKED_FOR]  WITH CHECK ADD  CONSTRAINT [FK_WORKED_FOR_PROFILE] FOREIGN KEY([profile_id])
REFERENCES [atzoum01].[PROFILE] ([profile_id])
GO
ALTER TABLE [atzoum01].[WORKED_FOR] CHECK CONSTRAINT [FK_WORKED_FOR_PROFILE]
GO
USE [master]
GO
ALTER DATABASE [atzoum01] SET  READ_WRITE 
GO
